version: '3.4'
services:
  cfssl:
    image: blackducksoftware/blackduck-cfssl:1.0.0
    volumes: ['cert-volume:/etc/cfssl']
    env_file: [blackduck-config.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8888/api/v1/cfssl/scaninfo']
      interval: 30s
      timeout: 10s
      retries: 5
    user: cfssl:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  logstash:
    image: blackducksoftware/blackduck-logstash:1.0.2
    volumes: ['log-volume:/var/lib/logstash/data']
    env_file: [blackduck-config.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:9600/']
      interval: 30s
      timeout: 10s
      retries: 5
    user: logstash:root
    environment: {DAYS_TO_KEEP_LOGS: 30}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 1024M}
        reservations: {memory: 1024M}
  registration:
    image: blackducksoftware/blackduck-registration:2018.12.0
    links: [logstash, cfssl]
    volumes:
    - config-volume:/opt/blackduck/hub/hub-registration/config
    - {type: tmpfs, target: /opt/blackduck/hub/hub-registration/security}
    env_file: [blackduck-config.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/registration/health-checks/liveness',
        /opt/blackduck/hub/hub-registration/security/root.crt, /opt/blackduck/hub/hub-registration/security/blackduck_system.crt,
        /opt/blackduck/hub/hub-registration/security/blackduck_system.key]
      interval: 30s
      timeout: 10s
      retries: 5
    user: tomcat:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  zookeeper:
    image: blackducksoftware/blackduck-zookeeper:1.0.0
    links: [logstash]
    volumes: ['zookeeper-data-volume:/opt/blackduck/zookeeper/data', 'zookeeper-datalog-volume:/opt/blackduck/zookeeper/datalog']
    env_file: [blackduck-config.env]
    healthcheck:
      test: [CMD, zkServer.sh, status, /opt/blackduck/zookeeper/conf/zoo.cfg]
      interval: 30s
      timeout: 10s
      retries: 5
    user: zookeeper:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 384M}
        reservations: {memory: 384M}
  solr:
    image: blackducksoftware/blackduck-solr:1.0.0
    links: [logstash, zookeeper]
    volumes: ['solr6-volume:/opt/blackduck/hub/solr/cores.data']
    env_file: [blackduck-config.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8983/solr/project/admin/ping?wt=json']
      interval: 30s
      timeout: 10s
      retries: 5
    user: solr:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  authentication:
    image: blackducksoftware/blackduck-authentication:2018.12.0
    links: [cfssl, logstash, registration, zookeeper, webapp]
    volumes:
    - authentication-volume:/opt/blackduck/hub/hub-authentication/ldap
    - {type: tmpfs, target: /opt/blackduck/hub/hub-authentication/security}
    env_file: [blackduck-config.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-authentication/security/root.crt, /opt/blackduck/hub/hub-authentication/security/blackduck_system.crt,
        /opt/blackduck/hub/hub-authentication/security/blackduck_system.key]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    user: authentication:root
    environment: {HUB_MAX_MEMORY: 512m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 1024M}
        reservations: {memory: 1024M}
  webapp:
    image: blackducksoftware/blackduck-webapp:2018.12.0
    links: [cfssl, logstash, registration, zookeeper, solr]
    volumes:
    - log-volume:/opt/blackduck/hub/logs
    - webapp-volume:/opt/blackduck/hub/hub-webapp/ldap
    - {type: tmpfs, target: /opt/blackduck/hub/hub-webapp/security}
    env_file: [blackduck-config.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-webapp/security/root.crt, /opt/blackduck/hub/hub-webapp/security/blackduck_system.crt,
        /opt/blackduck/hub/hub-webapp/security/blackduck_system.key]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    user: tomcat:root
    environment: {HUB_MAX_MEMORY: 2048m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 2560M}
        reservations: {cpus: '1', memory: 2560M}
  scan:
    image: blackducksoftware/blackduck-scan:2018.12.0
    links: [cfssl, logstash, registration, zookeeper]
    env_file: [blackduck-config.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-scan/security/root.crt, /opt/blackduck/hub/hub-scan/security/blackduck_system.crt,
        /opt/blackduck/hub/hub-scan/security/blackduck_system.key]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    user: tomcat:root
    environment: {HUB_MAX_MEMORY: 2048m}
    volumes:
    - {type: tmpfs, target: /opt/blackduck/hub/hub-scan/security}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 2560M}
        reservations: {cpus: '1', memory: 2560M}
  jobrunner:
    image: blackducksoftware/blackduck-jobrunner:2018.12.0
    links: [cfssl, logstash, registration, zookeeper, solr]
    env_file: [blackduck-config.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    user: jobrunner:root
    environment: {HUB_MAX_MEMORY: 4096m}
    volumes:
    - {type: tmpfs, target: /opt/blackduck/hub/jobrunner/security}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 4608M}
        reservations: {cpus: '1', memory: 4608M}
  webserver:
    image: blackducksoftware/blackduck-nginx:1.0.0
    ports: ['443:8443']
    env_file: [hub-webserver.env, blackduck-config.env]
    links: [webapp, cfssl, documentation, authentication, scan]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/health-checks/liveness',
        /opt/blackduck/hub/webserver/security/root.crt]
      interval: 30s
      timeout: 10s
      retries: 5
    user: nginx:root
    volumes:
    - {type: tmpfs, target: /opt/blackduck/hub/webserver/security}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 15s, window: 60s}
      resources:
        limits: {memory: 512M}
        reservations: {memory: 512M}
  documentation:
    image: blackducksoftware/blackduck-documentation:2018.12.0
    links: [logstash]
    env_file: [blackduck-config.env]
    user: tomcat:root
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://127.0.0.1:8443/hubdoc/health-checks/liveness',
        /opt/blackduck/hub/hub-documentation/security/root.crt]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - {type: tmpfs, target: /opt/blackduck/hub/hub-documentation/security}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 512M}
        reservations: {memory: 512M}
volumes: {authentication-volume: null, cert-volume: null, config-volume: null, log-volume: null,
  webapp-volume: null, solr6-volume: null, monitor-log-volume: null, zookeeper-data-volume: null,
  zookeeper-datalog-volume: null}
