apiVersion: v1
kind: List
metadata:
  name: hub
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hub-db-config-granular
  data:
    HUB_POSTGRES_ENABLE_SSL: "false"
    HUB_POSTGRES_ENABLE_SSL_CERT_AUTH: "false"
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: postgres
  spec:
    replicas: 1
    template:
      metadata:
        name: postgres
        labels:
          app: postgres
          tier: postgres
      spec:
        volumes:
        - name: postgres-persistent-vol
          emptyDir: {}
#        In some filesystems, red hat's postgres user (26) won't by default be able to write to directories.
#        This is a declarative way to fix this (will work iff you're allowed to run containers as uid 0).
#        initContainers:
#        - name: chmod
#        command: ["chown", "-R", "26:26", "/var/lib/pgsql/data/" ]
#        image: alpine
#        volumeMounts:
#        - name: postgres-persistent-vol
#          mountPath: /var/lib/pgsql/data
#          subPath: blackduck
#          readOnly: false
#        securityContext:
#          runAsUser: 0
        containers:
        - name: postgres
          image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:1
          resources:
            requests:
              memory: 3072M
              cpu: 1
          volumeMounts:
          - name: postgres-persistent-vol
            mountPath: /var/lib/pgsql/data
            subPath: blackduck
          envFrom:
          - configMapRef:
              name: hub-db-config
          - configMapRef:
              name: hub-db-config-granular
          env:
          - name: POSTGRESQL_USER
            value: blackduck
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: blackduck
          - name: POSTGRESQL_DATABASE
            value: blackduck
          - name: POSTGRESQL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: blackduck
          ports:
          - containerPort: 5432
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
    selector:
      app: postgres
  status:
    loadBalancer: {}
