kind: List
apiVersion: v1
items:
##
# This is a replacement for the 'webserver' service for Black Duck versions prior to 5.0.
# Before creating this service the previous service should be removed. One way to remove
# the previous service is with:
#
# kubectl --namespace=<ns> delete service webserver
#
# This is not needed for installing a new Black Duck 5.0 system or if upgrading
# from a version of Black Duck that is 5.0 or newer. 
##
- apiVersion: v1
  kind: Service
  metadata:
    name: webserver
  spec:
    ports:
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 8443
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: webserver
  status:
    loadBalancer: {}